# Generated by Django 5.0.6 on 2024-06-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE')),
                ('item_type', models.CharField(choices=[('GOODS', 'Goods'), ('SERVICES', 'Services')])),
                ('description', models.TextField(blank=True)),
                ('selling_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('PCS', 'Pcs'), ('KG', 'Kg'), ('LTR', 'Ltr'), ('MTR', 'Mtr')], default='PCS')),
                ('taxes_applicable', models.BooleanField(default=False)),
                ('tax_percentage_on_item', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('available_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
