# Generated by Django 5.0.6 on 2024-07-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='selling_rate',
            new_name='marked_price_by_user_for_sale',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='item',
            name='available_stock',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
