# Generated by Django 5.0.6 on 2024-07-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_inventory_threshold_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available_stock',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
