# Generated by Django 5.0.6 on 2024-06-22 11:08

import gst_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gstin',
            field=gst_field.modelfields.GSTField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
