# Generated by Django 5.0.6 on 2024-06-30 05:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_gstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='_aadhar_number',
            field=models.CharField(blank=True, db_column='aadhar_number', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='upi_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
