# Generated by Django 5.0.6 on 2024-06-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimates',
            name='upload_additional_files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
