# Generated by Django 5.0.6 on 2024-07-03 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0002_alter_estimates_upload_additional_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimateitems',
            old_name='item',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='estimates',
            name='estimate_date',
            field=models.DateField(default=datetime.date(2024, 7, 3)),
        ),
    ]
