# Generated by Django 5.0.6 on 2024-09-08 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0002_alter_estimateitems_quoteitems_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimates',
            old_name='spipping_charges',
            new_name='shipping_charges',
        ),
        migrations.AlterField(
            model_name='estimates',
            name='estimate_date',
            field=models.DateField(default=datetime.date(2024, 9, 8)),
        ),
    ]
