# Generated by Django 5.0.6 on 2024-07-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0003_rename_item_estimateitems_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimateitems',
            old_name='quantity',
            new_name='offered_quantity_to_customer',
        ),
        migrations.RenameField(
            model_name='estimateitems',
            old_name='price',
            new_name='selling_price_proposed_to_customer',
        ),
    ]
