# Generated by Django 5.0.6 on 2024-09-14 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0004_remove_estimateitems_estimate_estimates_items_and_more'),
        ('items', '0005_alter_item_available_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimates',
            name='items',
        ),
        migrations.AddField(
            model_name='estimateitems',
            name='estimate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estimates.estimates'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimates',
            name='offered_estimate_items',
            field=models.ManyToManyField(through='estimates.EstimateItems', to='items.item'),
        ),
    ]
