# Generated by Django 5.0.6 on 2024-07-03 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0004_rename_quantity_estimateitems_offered_quantity_to_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateitems',
            name='selling_price_proposed_to_customer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estimates',
            name='estimate_date',
            field=models.DateField(default=datetime.date(2024, 7, 4)),
        ),
    ]
