# Generated by Django 5.0.6 on 2024-07-12 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0005_alter_estimateitems_selling_price_proposed_to_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimates',
            name='estimate_date',
            field=models.DateField(default=datetime.date(2024, 7, 12)),
        ),
    ]
