# Generated by Django 5.0.6 on 2024-09-20 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0005_remove_estimates_items_estimateitems_estimate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimateitems',
            old_name='quoteitems_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='estimates',
            name='estimate_date',
            field=models.DateField(default=datetime.date(2024, 9, 20)),
        ),
    ]
