# Generated by Django 5.0.6 on 2024-07-13 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0006_alter_estimates_estimate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimates',
            name='total_estimate_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='estimates',
            name='estimate_date',
            field=models.DateField(default=datetime.date(2024, 7, 13)),
        ),
    ]
