# Generated by Django 5.0.6 on 2024-09-20 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0006_rename_quoteitems_id_estimateitems_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateitems',
            name='estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimates.estimates'),
        ),
    ]
