# Generated by Django 5.0.6 on 2024-09-21 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0007_alter_estimateitems_estimate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimates',
            old_name='offered_estimate_items',
            new_name='items',
        ),
        migrations.AlterField(
            model_name='estimates',
            name='estimate_date',
            field=models.DateField(default=datetime.date(2024, 9, 21)),
        ),
    ]
