# Generated by Django 5.0.6 on 2024-09-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0008_rename_offered_estimate_items_estimates_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimateitems',
            old_name='product',
            new_name='name',
        ),
    ]
